import {type GenreType } from './genre';

export type OdaiData = {
	value: string;
	id: number;
}

export const list: {
	[key in GenreType]: OdaiData[]
} = {
	shiritori: [
		{ value: 'りんご', id: 1 },
		{ value: 'ごりら', id: 2 },
		{ value: 'らっぱ', id: 3 },
		{ value: 'ぱんだ', id: 4 },
		{ value: 'だんご', id: 5 },
		{ value: 'ごま', id: 6 },
		{ value: 'まぐろ', id: 7 },
		{ value: 'ろうそく', id: 8 },
		{ value: 'くつ', id: 9 },
		{ value: 'つばめ', id: 10 },
		{ value: 'めだか', id: 11 },
		{ value: 'かば', id: 12 },
		{ value: 'ばなな', id: 13 },
		{ value: 'なす', id: 14 },
		{ value: 'すいか', id: 15 },
		{ value: 'かき', id: 16 },
		{ value: 'きつね', id: 17 },
		{ value: 'ねずみ', id: 18 },
		{ value: 'りす', id: 19 },
		{ value: 'すずめ', id: 20 },
		{ value: 'めだま', id: 21 },
		{ value: 'まんじゅう', id: 22 },
		{ value: 'うさぎ', id: 23 },
		{ value: 'さば', id: 24 },
		{ value: 'こうそく', id: 25 },
		{ value: 'くち', id: 26 },
		{ value: 'するめ', id: 27 },
		{ value: 'あたま', id: 28 },
		{ value: 'かばん', id: 29 },
		{ value: 'くすり', id: 20 },
	],
	gesture: [
		{ value: "宇宙旅行", id: 1 },
		{ value: "恐竜", id: 2 },
		{ value: "魔法使い", id: 3 },
		{ value: "ロボット", id: 4 },
		{ value: "海賊", id: 5 },
		{ value: "忍者", id: 6 },
		{ value: "スーパーヒーロー", id: 7 },
		{ value: "お化け屋敷", id: 8 },
		{ value: "サーカス", id: 9 },
		{ value: "探偵", id: 10 },
		{ value: "タイムトラベル", id: 11 },
		{ value: "ドラゴン", id: 12 },
		{ value: "宇宙人", id: 13 },
		{ value: "宝探し", id: 14 },
		{ value: "ミステリー", id: 15 },
		{ value: "冒険", id: 16 },
		{ value: "ファンタジー", id: 17 },
		{ value: "スポーツ大会", id: 18 },
		{ value: "音楽フェス", id: 19 },
		{ value: "映画撮影", id: 20 },
		{ value: "料理コンテスト", id: 21 },
		{ value: "ファッションショー", id: 22 },
		{ value: "動物園", id: 23 },
		{ value: "水族館", id: 24 },
		{ value: "遊園地", id: 25 },
		{ value: "博物館", id: 26 },
		{ value: "美術館", id: 27 },
		{ value: "図書館", id: 28 },
		{ value: "カフェ", id: 29 },
		{ value: "ショッピングモール", id: 30 },
		{ value: "スパイダーマン", id: 31 },
		{ value: "ハリーポッター", id: 32 },
		{ value: "ゴジラ", id: 33 },
		{ value: "ドラえもん", id: 34 },
		{ value: "ピカチュウ", id: 35 }
	],
	quiz: [
		{ value: "歴史", id: 1 },
		{ value: "地理", id: 2 },
		{ value: "科学", id: 3 },
		{ value: "文学", id: 4 },
		{ value: "音楽", id: 5 },
		{ value: "映画", id: 6 },
		{ value: "スポーツ", id: 7 },
		{ value: "アート", id: 8 },
		{ value: "テクノロジー", id: 9 },
		{ value: "政治", id: 10 },
		{ value: "経済", id: 11 },
		{ value: "数学", id: 12 },
		{ value: "生物学", id: 13 },
		{ value: "化学", id: 14 },
		{ value: "物理学", id: 15 },
		{ value: "天文学", id: 16 },
		{ value: "哲学", id: 17 },
		{ value: "心理学", id: 18 },
		{ value: "宗教", id: 19 },
		{ value: "言語学", id: 20 },
		{ value: "社会学", id: 21 },
		{ value: "法律", id: 22 },
		{ value: "医学", id: 23 },
		{ value: "環境学", id: 24 },
		{ value: "教育", id: 25 },
		{ value: "ファッション", id: 26 },
		{ value: "料理", id: 27 },
		{ value: "旅行", id: 28 },
		{ value: "アニメ", id: 29 },
		{ value: "マンガ", id: 30 },
		{ value: "テレビ番組", id: 31 },
		{ value: "ビデオゲーム", id: 32 },
		{ value: "有名人", id: 33 },
		{ value: "ブランド", id: 34 },
		{ value: "動物", id: 35 },
		{ value: "植物", id: 36 },
		{ value: "食べ物", id: 37 },
		{ value: "飲み物", id: 38 },
		{ value: "乗り物", id: 39 },
		{ value: "建築", id: 40 }
	],
	// 連想ゲームのお題 答えではなくお題、テーマ
	yamanote: [
		{ value: "犬", id: 1 },
		{ value: "猫", id: 2 },
		{ value: "車", id: 3 },
		{ value: "飛行機", id: 4 },
		{ value: "電車", id: 5 },
		{ value: "自転車", id: 6 },
		{ value: "バス", id: 7 },
		{ value: "船", id: 8 },
		{ value: "ピアノ", id: 9 },
		{ value: "ギター", id: 10 },
		{ value: "ドラム", id: 11 },
		{ value: "バイオリン", id: 12 },
		{ value: "サッカー", id: 13 },
		{ value: "バスケットボール", id: 14 },
		{ value: "野球", id: 15 },
		{ value: "テニス", id: 16 },
		{ value: "ゴルフ", id: 17 },
		{ value: "スキー", id: 18 },
		{ value: "スケート", id: 19 },
		{ value: "水泳", id: 20 },
		{ value: "料理", id: 21 },
		{ value: "掃除", id: 22 },
		{ value: "洗濯", id: 23 },
		{ value: "読書", id: 24 },
		{ value: "映画", id: 25 },
		{ value: "ダンス", id: 26 },
		{ value: "歌", id: 27 },
		{ value: "絵", id: 28 },
		{ value: "花火", id: 29 },
		{ value: "海", id: 30 }
	]
	,
	freeTalk:[
		{ value: "最近読んだ本", id: 1 },
		{ value: "好きな映画", id: 2 },
		{ value: "旅行したい場所", id: 3 },
		{ value: "趣味について", id: 4 },
		{ value: "好きな食べ物", id: 5 },
		{ value: "休日の過ごし方", id: 6 },
		{ value: "子供の頃の思い出", id: 7 },
		{ value: "最近見た夢", id: 8 },
		{ value: "好きな音楽", id: 9 },
		{ value: "将来の目標", id: 10 },
		{ value: "ペットについて", id: 11 },
		{ value: "好きなスポーツ", id: 12 },
		{ value: "最近のニュース", id: 13 },
		{ value: "好きな季節", id: 14 },
		{ value: "仕事について", id: 15 },
		{ value: "家族について", id: 16 },
		{ value: "好きなテレビ番組", id: 17 },
		{ value: "最近の出来事", id: 18 },
		{ value: "好きな場所", id: 19 },
		{ value: "好きなアニメ", id: 20 },
		{ value: "好きなマンガ", id: 21 },
		{ value: "好きなゲーム", id: 22 },
		{ value: "好きな飲み物", id: 23 },
		{ value: "好きなブランド", id: 24 },
		{ value: "好きなファッション", id: 25 },
		{ value: "好きな動物", id: 26 },
		{ value: "好きな植物", id: 27 },
		{ value: "好きな花", id: 28 },
		{ value: "好きな色", id: 29 },
		{ value: "好きな言葉", id: 30 }
	]
}